import { expect, test } from "@playwright/test";
import { waitForHydration } from "./helpers/hydration";

test("mobile navigation traps keyboard focus, restores it on Escape, and follows links", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/");
  await waitForHydration(page);
  const trigger = page.getByRole("button", { name: "Open navigation" });
  await trigger.focus();
  await page.keyboard.press("Enter");
  const dialog = page.getByRole("dialog", { name: "Navigation" });
  const close = dialog.getByRole("button", { name: "Close navigation" });
  const first = dialog.getByRole("link", { name: "ApplyPack home" });
  const last = dialog.getByRole("link", { name: "Find My 10 Jobs" });
  await expect(close).toBeFocused();
  await expect(trigger).toHaveAttribute("aria-expanded", "true");
  await page.keyboard.press("Shift+Tab");
  await expect(first).toBeFocused();
  await page.keyboard.press("Shift+Tab");
  await expect(last).toBeFocused();
  await page.keyboard.press("Tab");
  await expect(first).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);
  await expect(trigger).toBeFocused();
  await expect(trigger).toHaveAttribute("aria-expanded", "false");
  expect(await page.locator("body").evaluate((body) => body.style.overflow)).not.toBe("hidden");
  await page.keyboard.press("Enter");
  await dialog.getByRole("link", { name: "Contact", exact: true }).click();
  // The destination may need its first development compilation on this worker.
  await page.waitForURL(/\/contact$/, { timeout: 30_000 });
  await expect(page).toHaveURL(/\/contact$/);
  await expect(dialog).toHaveCount(0);
  await expect(page.locator("main h1")).toBeVisible();
});

test("illustrative match tabs expose one panel and support arrow, Home, and End keys", async ({ page }) => {
  await page.goto("/");
  await waitForHydration(page);
  const tabs = page.getByRole("tablist", { name: "Reasons this illustrative job made the list" });
  const experience = tabs.getByRole("tab", { name: "Experience fit" });
  const life = tabs.getByRole("tab", { name: "Life fit" });
  const caveat = tabs.getByRole("tab", { name: "What to know" });
  await expect(experience).toHaveAttribute("aria-selected", "true");
  await experience.focus();
  await page.keyboard.press("ArrowRight");
  await expect(life).toBeFocused();
  await expect(life).toHaveAttribute("aria-selected", "true");
  await expect(experience).toHaveAttribute("tabindex", "-1");
  await expect(page.getByRole("tabpanel", { name: "Life fit", exact: true })).toBeVisible();
  await expect(page.getByRole("tabpanel", { name: "Experience fit", exact: true })).toHaveCount(0);
  await page.keyboard.press("End");
  await expect(caveat).toBeFocused();
  await expect(page.getByRole("tabpanel", { name: "What to know", exact: true })).toContainText("prefers direct client-onboarding experience");
  await page.keyboard.press("ArrowRight");
  await expect(experience).toBeFocused();
  await page.keyboard.press("ArrowLeft");
  await expect(caveat).toBeFocused();
  await page.keyboard.press("Home");
  await expect(experience).toBeFocused();
  await expect(experience).toHaveAttribute("aria-selected", "true");
});

test("homepage example, process, and FAQ controls respond to keyboard activation", async ({ page }) => {
  await page.goto("/");
  await waitForHydration(page);
  const example = page.getByRole("button", { name: "Small business", exact: true });
  await example.focus();
  await page.keyboard.press("Space");
  await expect(example).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByRole("button", { name: "Teaching", exact: true })).toHaveAttribute("aria-pressed", "false");
  await expect(page.locator(".brief-connector-panels")).toContainText("Purchasing Coordinator");
  const step = page.getByRole("button", { name: /Get application materials for the jobs you choose/ });
  await step.focus();
  await page.keyboard.press("Enter");
  await expect(step).toHaveAttribute("aria-expanded", "true");
  await expect(page.locator("#process-step-detail")).toContainText("$8 per selected job");
  const question = page.locator(".brief-faq details").filter({ hasText: "Does ApplyPack apply to jobs for me?" });
  await question.locator("summary").focus();
  await page.keyboard.press("Enter");
  await expect(question).toHaveAttribute("open", "");
  await expect(question.locator("p")).toBeVisible();
  await expect(question.locator("p")).toContainText("submit each application yourself");
  await page.keyboard.press("Space");
  await expect(question).not.toHaveAttribute("open", "");
  await expect(question.locator("p")).toBeHidden();
});
