"use client";
import { useState } from "react";
import { MatchingGuidedControls } from "./matching-guided-controls";
import { ManualResearchControls } from "./manual-research-controls";
export function MatchingWorkbench(){
 const [snapshot,setSnapshot]=useState("");const [packet,setPacket]=useState<unknown>(null);const [payload,setPayload]=useState("");const [endpoint,setEndpoint]=useState("matching-research");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 async function run(load=false){setBusy(true);try{const response=await fetch(load?`/api/admin/matching-research?snapshotId=${encodeURIComponent(snapshot)}`:`/api/admin/${endpoint}`,load?{cache:"no-store"}:{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(JSON.parse(payload))});const result=await response.json();if(!response.ok)throw new Error(result.error||"Review request failed");if(load)setPacket(result);else setMessage(JSON.stringify(result));}catch(e){setMessage(e instanceof Error?e.message:"Review failed");}finally{setBusy(false);}}
 return <section aria-labelledby="matching-workbench"><h2 id="matching-workbench">Research and evidence authoring</h2><p>Use current immutable criteria and source evidence. Questions and unanswered requirements remain unresolved. Recording a review does not release jobs.</p><label>Criteria snapshot ID<input value={snapshot} onChange={e=>setSnapshot(e.target.value)}/></label><button disabled={busy||!snapshot} onClick={()=>run(true)}>Load private review packet</button>
 {packet!==null&&<details><summary>Criteria, facts, coverage, evaluations and reviews</summary><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{JSON.stringify(packet,null,2)}</pre></details>}
 {packet!==null&&<MatchingGuidedControls snapshotId={snapshot} packet={packet} onPrepare={(target,value)=>{setEndpoint(target);setPayload(JSON.stringify(value,null,2));setMessage("Prepared from the selected evidence. Review it and validate below.");}}/>}
 {packet!==null&&<ManualResearchControls packet={packet} onPrepare={value=>{setEndpoint("matching-research");setPayload(JSON.stringify(value,null,2));setMessage("Review the manual checklist before recording it below.");}}/>}
 <label>Operation<select value={endpoint} onChange={e=>setEndpoint(e.target.value)}><option value="matching-research">Research round, verified snapshot admission or candidate question</option><option value="matching-reviews">Evidence or equivalence review</option><option value="matching-evaluations">Evaluate current reviews</option><option value="job-source-manual-observations">Record an official manual source observation</option></select></label>
 {endpoint==="job-source-manual-observations"&&<div><h3>Official listing observed by an operator</h3><p>Use a source with current manual permission. Open and inspect the official listing and application path yourself; record the exact text and check time within the last 15 minutes. This action does not activate collection or publish the job.</p><ol><li>Provide a new <code>observationId</code> UUID and a <code>posting</code> object with <code>sourceId</code>, <code>employerName</code>, <code>title</code> and <code>externalJobId</code> (null if unknown). Optional fields: location, employmentType, salaryMin, salaryMax, salaryCurrency, payPeriod, eligibleStates, eligibleCountries, closingAt. Preserve unknown values.</li><li>Provide a <code>review</code> object with <code>checkedAt</code> (ISO time), <code>officialListingUrl</code>, <code>officialApplicationUrl</code>, <code>capturedText</code>, <code>evidenceNotes</code> and <code>transitionReason</code> (both at least 20 characters). Set employerIdentityConfirmed, applicationPathConfirmed, listingActiveConfirmed and legitimacyConfirmed to true only after actually verifying each fact. Use lifecycleAction UNCHANGED, CHANGED or REOPENED to match the actual transition.</li><li>Validate the operation below. Keep its returned jobSnapshotId, then use matching-research ADMIT with the exact criteria snapshotId and inventoryVersionId. Complete the candidate evidence evaluation and bounded manual checklist separately.</li></ol><p>Reuse the same observationId only for an identical retry. A changed listing requires fresh evidence and an explicit transition reason.</p></div>}
 <p>COMPLETE_CELL with cellId, runId and evidence notes records complete research only after every listing has verified snapshot and evaluation evidence. Research: BEGIN with snapshotId, configurationIds and round (1–3); ADMIT with snapshotId, inventoryVersionId and jobSnapshotId; QUESTION with snapshotId, jobSnapshotId, nodeId and prompt. Evidence review requires exact source nodes, confirmed fact versions and rationale. Evaluation accepts review IDs, never scores or supplied gate results.</p>
 <label>Reviewed operation JSON<textarea rows={12} value={payload} onChange={e=>setPayload(e.target.value)} spellCheck={false}/></label><button disabled={busy||!payload} onClick={()=>run()}>Validate and record evidence</button><p role="status">{message}</p></section>;
}
