export type ContentSection = { title: string; body?: string[]; bullets?: string[]; note?: string };
export type PublicPage = {
  slug: string; eyebrow: string; title: string; seoTitle: string; description: string;
  intro: string[]; sections: ContentSection[]; ctaLabel?: string; ctaHref?: string;
};

const start = { ctaLabel: "Start My Search", ctaHref: "/get-started" };

export const publicPages: Record<string, PublicPage> = {
  "how-it-works": {
    slug: "how-it-works", eyebrow: "FROM \"I NEED A JOB\" TO READY TO APPLY",
    title: "From \"I need a job\" to ready to apply.",
    seoTitle: "24-Hour Job Search and Application Help | ApplyPack",
    description: "Tell ApplyPack what fits your life. Receive 10 matched jobs within 24 hours, then add tailored application materials for the jobs you choose.",
    intro: ["ApplyPack handles the work between needing something different and having an application ready to submit.", "You do not need the perfect job title or resume. You only need to give us somewhere honest to start."],
    sections: [
      { title: "1. Tell us what stays and what goes.", body: ["Your pay, location, schedule, priorities, and dealbreakers shape the search."] },
      { title: "2. We look past your old title.", body: ["We review work, side businesses, volunteering, caregiving periods, education, and other relevant experience to understand the skills underneath the titles."] },
      { title: "3. We find 10 current opportunities.", body: ["We search around the exact criteria you approve. We do not give you another endless results page."] },
      { title: "4. We explain every match.", bullets: ["Company and job title", "Direct application link", "Location and salary when listed", "Why it may fit", "Requirements, visible gaps, and date checked"] },
      { title: "5. You choose.", body: ["Select one, several, all 10, or none. You do not buy application materials for jobs you do not want."] },
      { title: "6. We build around the job.", body: ["For $8 per selected job, ApplyPack creates a truthful, tailored resume and cover letter."] },
      { title: "7. You review and apply.", body: ["You receive editable documents within 24 hours, review every detail, and submit the application yourself."] },
      { title: "What ApplyPack is not", bullets: ["A staffing agency or employer", "A job board or auto-apply bot", "A guarantee of an interview", "A service that invents qualifications"] },
    ], ...start,
  },
  "job-search-help": {
    slug: "job-search-help", eyebrow: "YOU DO NOT HAVE TO KNOW THE JOB TITLE YET",
    title: "You do not have to know the job title yet.",
    seoTitle: "Job Search Help Without Knowing the Job Title | ApplyPack",
    description: "Know what you want, or only what you do not want? ApplyPack searches around your pay, schedule, location, and career priorities.",
    intro: ["Maybe you know you want remote work, $80K+, benefits, and no sales. That is enough to begin."],
    sections: [
      { title: "Tell us what stays.", bullets: ["Remote work", "Minimum salary", "Benefits or flexibility", "Limited travel", "A location or time zone"] },
      { title: "Tell us what goes.", bullets: ["Sales or marketing", "Cold calling", "Heavy phone work", "Travel, nights, or weekends"] },
      { title: "We search between the two.", body: ["Your past can still matter without sending you back into the same kind of job."] },
      { title: "No padding the list.", body: ["If the criteria produce fewer than 10 reasonable opportunities, we tell you and ask before changing a preference."] },
      { title: "A match is not a guarantee.", body: ["Employers decide whom to interview. You decide whether a job is right for you."] },
    ], ...start,
  },
  "experience-connections": {
    slug: "experience-connections", eyebrow: "YOUR EXPERIENCE MAY FIT MORE JOBS THAN YOU THINK",
    title: "Your experience may fit more jobs than you think. ApplyPack makes the connection.",
    seoTitle: "What Jobs Fit My Experience? | ApplyPack",
    description: "Your experience may fit more roles than you think. See how ApplyPack connects real skills from work, caregiving periods, and side businesses to new jobs.",
    intro: ["A title is a label. The work underneath it is often much broader."],
    sections: [
      { title: "Small business", body: ["Ordering, pricing, customer communication, deadlines, costs, and problem solving may connect to operations or order management."] },
      { title: "Teaching", body: ["Training, documentation, planning, progress tracking, and facilitation may connect to onboarding or program coordination."] },
      { title: "Retail supervision", body: ["Scheduling, inventory, coaching, escalations, and reporting may connect to operations support."] },
      { title: "Administrative work", body: ["Records, follow-up, vendor communication, and document preparation may connect to project coordination."] },
      { title: "Time outside traditional work", body: ["Life periods can explain a timeline, but ApplyPack never relabels unpaid responsibilities as employment."] },
      { title: "The trust boundary", body: ["We surface genuine overlap, keep important gaps visible, and never invent titles, dates, credentials, or outcomes."] },
    ], ...start,
  },
  "before-and-after": {
    slug: "before-and-after", eyebrow: "SEE WHAT CHANGES WHEN THE JOB COMES FIRST",
    title: "See what changes when the job comes first.",
    seoTitle: "Resume Before and After for a Career Change | ApplyPack",
    description: "See how ApplyPack connects a real background to a different role, then changes the resume and cover letter to make the fit clear.",
    intro: ["Illustrative example based on a common career-change scenario. This is not a customer testimonial."],
    sections: [
      { title: "Before: generic", body: ["Developed lesson plans. Communicated with families. Maintained student records."] },
      { title: "After: client onboarding", body: ["Created clear instructional materials, guided people through unfamiliar processes, tracked progress, and adjusted support when barriers arose."] },
      { title: "What changed", bullets: ["Relevant work moved forward", "Language became clearer", "Original facts stayed intact", "Missing requirements remained visible"] },
      { title: "The cover letter changes too.", body: ["It explains why this employer, why this role, and where your real experience may transfer."] },
    ], ...start,
  },
  "resume-screening": {
    slug: "resume-screening", eyebrow: "RESUME SCREENING",
    title: "Before a person really looks at your resume, software may already be sorting it.",
    seoTitle: "How Resume Screening Software Reads Applications | ApplyPack",
    description: "Learn how hiring software may sort your resume before a recruiter reviews it, and how ApplyPack prepares documents for software and people.",
    intro: ["The safest strategy is a clean document that uses relevant language accurately."],
    sections: [
      { title: "What we do", bullets: ["Readable structure", "Relevant experience first", "Accurate job language", "Truthful dates and credentials", "Editable Word delivery"] },
      { title: "What we do not do", bullets: ["Stuff keywords", "Hide text", "Invent qualifications", "Claim a guaranteed score", "Promise an interview"] },
      { title: "Human review matters.", body: ["A person reviews every document before delivery. You review it again before submitting."] },
    ], ...start,
  },
  "not-just-ai": {
    slug: "not-just-ai", eyebrow: "NOT JUST ANOTHER AI RESUME",
    title: "Not just another AI resume.",
    seoTitle: "Human-Reviewed Resume and Cover Letter Service | ApplyPack",
    description: "ApplyPack uses technology for speed and human judgment for accuracy. No fake experience, invented numbers, or generic application materials.",
    intro: ["AI-assisted tools may support research, comparison, and drafting. They do not make the final decision about what reaches you."],
    sections: [
      { title: "Research needs judgment.", body: ["Keywords can match while salary, schedule, or location does not."] },
      { title: "Connections need restraint.", body: ["Similar language is not permission to invent a qualification."] },
      { title: "Writing needs context.", body: ["Documents must match the selected job and remain consistent with your source material."] },
      { title: "Every delivery is reviewed.", bullets: ["Criteria checked", "Links checked", "Claims checked against customer facts", "Clarity and consistency reviewed"] },
    ], ...start,
  },
  pricing: {
    slug: "pricing", eyebrow: "PAY FOR THE HELP YOU ACTUALLY USE",
    title: "Pay for the help you actually use.",
    seoTitle: "ApplyPack Pricing | 10 Job Matches in 24 Hours for $20",
    description: "Receive 10 matched job opportunities within 24 hours for $20. Add a tailored resume and cover letter within 24 hours for $8 per selected job.",
    intro: ["No subscription. No recurring charge. No auto-apply service."],
    sections: [
      { title: "$20 Job Match Search", bullets: ["10 current opportunities", "Direct links", "Fit and gap explanations", "Delivered within 24 hours of completed intake and payment"] },
      { title: "$8 Apply Pack, per job", bullets: ["One tailored resume", "One tailored cover letter", "Editable Word documents", "Human review", "One factual-correction round"] },
      { title: "Two selected jobs", body: ["$20 search + $16 application materials = $36 total."] },
      { title: "All 10 selected jobs", body: ["$20 search + $80 application materials = $100 total."] },
      { title: "The search stands alone.", body: ["Choose one, all 10, or none. A material conflict with an approved non-negotiable is eligible for replacement review."] },
    ], ctaLabel: "Get My 10 Jobs in 24 Hours", ctaHref: "/get-started",
  },
  faq: {
    slug: "faq", eyebrow: "CLEAR BEFORE YOU PAY", title: "Questions before you start?",
    seoTitle: "Job Search and Resume Help FAQ | ApplyPack",
    description: "Answers about job matching, career changes, resume gaps, tailored cover letters, turnaround, delivery, revisions, privacy, and ApplyPack's limits.",
    intro: ["If your question is not here, contact us before purchasing."],
    sections: [
      { title: "What if I do not know what job I want?", body: ["Start with what fits your life and what you do not want to do again."] },
      { title: "Do I need a resume?", body: ["Yes. It can be old or written for another career. It provides the factual starting point."] },
      { title: "When does 24 hours begin?", body: ["After completed, approved intake and payment. For Apply Packs, after selection confirmation and payment."] },
      { title: "Does that include weekends?", body: ["Yes. When the queue is full, purchases pause."] },
      { title: "Must I buy all 10 Apply Packs?", body: ["No. Choose one, several, all 10, or none."] },
      { title: "What if a job conflicts with my criteria?", body: ["A material conflict with an approved non-negotiable is reviewed and replaced at no charge."] },
      { title: "Does ApplyPack submit applications?", body: ["No. You review and submit each application yourself."] },
      { title: "Is an interview guaranteed?", body: ["No. Employers make every hiring decision."] },
      { title: "Does ApplyPack use AI?", body: ["AI-assisted tools may help, and a person reviews every delivery."] },
      { title: "Is my information private?", body: ["It is used to provide the service and is not sold."] },
      { title: "Are you a recruiter?", body: ["No. ApplyPack works for the job seeker."] },
    ], ctaLabel: "Ask Another Question", ctaHref: "/contact",
  },
  about: {
    slug: "about", eyebrow: "A MORE HUMAN PLACE TO START", title: "I built ApplyPack because I needed it.",
    seoTitle: "About ApplyPack | A More Human Job Search Service",
    description: "ApplyPack was created for people with real experience who need help finding where it fits next.",
    intro: ["I had years of experience and time outside the traditional workforce. I knew what I did not want, but not which titles to search."],
    sections: [
      { title: "So I built a process.", body: ["I learned to search beyond titles, compare the work inside a posting, connect transferable experience, and tailor applications without making anything up."] },
      { title: "Marissa Wright", bullets: ["Founder of ApplyPack", "Former teacher", "Private-label e-commerce operations", "Career changer"] },
      { title: "We work for the applicant.", body: ["ApplyPack is not a recruiter or staffing agency."] },
    ], ...start,
  },
  contact: {
    slug: "contact", eyebrow: "CONTACT APPLYPACK", title: "How can we help?",
    seoTitle: "Contact ApplyPack | Job Search and Resume Help",
    description: "Questions about job matching, tailored resumes, cover letters, an order, or website accessibility? Contact ApplyPack.",
    intro: ["We normally respond within two business days. Do not email resumes, payment details, or other sensitive documents."],
    sections: [
      { title: "General help, privacy, and accessibility", body: ["help@applypack.work"] },
      { title: "Orders and billing", body: ["orders@applypack.work"] },
    ], ctaLabel: "Email Help", ctaHref: "mailto:help@applypack.work",
  },
  accessibility: {
    slug: "accessibility", eyebrow: "ACCESSIBILITY AT APPLYPACK", title: "Accessibility at ApplyPack",
    seoTitle: "Accessibility Statement | ApplyPack",
    description: "ApplyPack's accessibility target and support contact.",
    intro: ["DuoTap LLC d/b/a ApplyPack is committed to a website and service usable by as many people as possible."],
    sections: [
      { title: "Our target", body: ["We aim to conform to WCAG 2.2 Level AA."], bullets: ["Keyboard access", "Visible focus", "Clear structure and labels", "Sufficient contrast", "Reflow and reduced motion", "Manual and automated testing"] },
      { title: "Need help or another format?", body: ["Email help@applypack.work with the page or service step, what happened, the accommodation or alternative you need, and how you prefer us to respond. We will work with you to provide the service through an accessible alternative when reasonably possible."] },
      { title: "Ongoing work", body: ["Accessibility is reviewed during design, development, content changes, and major releases. Automated checks support, but do not replace, keyboard, reflow, screen-reader, and human review."], note: "Operational draft. Last reviewed September 2, 2026; not a certification of complete conformance." },
    ], ctaLabel: "Email Accessibility Help", ctaHref: "mailto:help@applypack.work",
  },
  privacy: {
    slug: "privacy", eyebrow: "PRIVACY POLICY", title: "Your information is for providing your service.",
    seoTitle: "Privacy Policy | ApplyPack",
    description: "How ApplyPack, operated by DuoTap LLC d/b/a ApplyPack, handles information.",
    intro: ["Effective September 2, 2026. This operational draft describes the service as implemented and is not labeled attorney-approved."],
    sections: [
      { title: "Information and use", body: ["We collect contact details, approved search criteria and preferences, documents you upload, order and delivery records, support messages, and limited operational security logs. We use them to authenticate you, perform and deliver the service, take payment, provide support, prevent abuse, and meet legal or accounting obligations."] },
      { title: "AI assistance and human review", body: ["AI-assisted tools may support research, comparison, and drafting. They do not make a final customer-facing delivery decision. A person must review every delivered job list, resume, and cover letter, and factual claims must remain grounded in information you provide."] },
      { title: "Uploads and document safety", body: ["Uploads are kept in private account storage with randomized storage keys and restricted access. Supported files are checked for allowed type, size, file structure, and prohibited active content. ApplyPack does not claim that files receive a complete malware scan unless the service expressly says so."] },
      { title: "Providers", body: ["Supabase supports authentication, database, and private file storage; Railway hosts the application; Stripe processes payments; and configured email providers deliver authentication, order, and support messages. A provider receives only the information reasonably needed for its function. Payment metadata uses internal identifiers rather than resume text, private documents, or intake narratives."] },
      { title: "Payments and email", body: ["Stripe processes card details; ApplyPack does not store full card numbers. Authentication and transactional messages are sent to the email address associated with your account. Public support is available at help@applypack.work."] },
      { title: "Sharing and analytics", body: ["We do not sell resumes or personal information. At launch, ApplyPack does not use advertising pixels, heatmaps, session replay, or customer behavioral analytics. We share information only as needed to provide or secure the service, comply with law, resolve a transaction, or follow your direction."] },
      { title: "Retention and security", body: ["Saved intake drafts expire after seven days. Source documents are scheduled for deletion 30 days after intake, with the due date refreshed to 30 days after completed search delivery when the documents are still needed for that service; order, delivery, audit, and legally required transaction records may be retained longer. Access is restricted by account and role, admin access requires a stronger authentication level, and signed links are time-limited. No system can promise absolute security."] },
      { title: "Your choices", body: ["Email help@applypack.work for access, correction, or deletion requests. Some records may be retained for transactions, disputes, security, or law."] },
      { title: "Children and changes", body: ["ApplyPack is not directed to children under 18. Changes will be posted with a new effective date."] },
    ], ctaLabel: "Contact Privacy", ctaHref: "mailto:help@applypack.work",
  },
  terms: {
    slug: "terms", eyebrow: "TERMS OF SERVICE", title: "The service boundary, in plain language.",
    seoTitle: "Terms of Service | ApplyPack",
    description: "Terms for ApplyPack's job-search and application-preparation services.",
    intro: ["Effective September 2, 2026. ApplyPack is operated by DuoTap LLC d/b/a ApplyPack. This is an operational draft and is not labeled attorney-approved."],
    sections: [
      { title: "Service and eligibility", body: ["ApplyPack serves customers 18 or older and is not a recruiter, employer, staffing agency, or law firm. ApplyPack researches and prepares materials; it does not contact employers or submit applications for customers."] },
      { title: "$20 Job Match Search", body: ["The $20 fee pays for ApplyPack's research and delivery of exactly 10 opportunities that conform to the criteria you approved. The 24-clock-hour period begins only after a complete intake, your approval of the criteria, verified payment, and displayed capacity. If 10 qualifying opportunities cannot be found without changing those criteria, ApplyPack will not pad the list and will ask you before changing a preference."] },
      { title: "$8 Apply Pack", body: ["Each $8 unit covers one truthful, tailored resume and one truthful, tailored cover letter for one job you select from your delivered list. The 24-clock-hour period begins after selection confirmation, verified payment, and available capacity. Every delivery requires human review."] },
      { title: "Your review and responsibility", body: ["Provide accurate facts and documents you have the right to use, review each delivery, answer employer questions, and submit applications yourself. ApplyPack will not invent titles, dates, credentials, experience, achievements, or other qualifications."] },
      { title: "Search completeness, final delivery, and replacement", body: ["Delivery of 10 properly matched opportunities completes the purchased search, and the delivered search is non-refundable. A job counts toward the 10 even if you later decide you do not personally like or want it. If a delivered job materially violates an approved non-negotiable, ApplyPack will review it and replace it at no additional charge rather than refunding the completed search. This does not limit a remedy required by applicable law or correction of a duplicate or incorrect charge."] },
      { title: "Corrections", body: ["One factual-correction round is included for each Apply Pack when requested within three calendar days of delivery. A factual correction is not free retargeting to a different job, a new career strategy, a completely different writing approach, or incorporation of brand-new experience supplied after completion."] },
      { title: "Closed or changed jobs", body: ["Jobs can close or change after ApplyPack verifies them. If a selected job closes after Apply Pack payment but before resume or cover-letter work begins, you may transfer the $8 payment to another valid job from the same delivered list or receive a refund for that unfinished Apply Pack. Once the completed resume and cover letter have been delivered, the Apply Pack is non-refundable even if the employer later closes or changes the job, except where a remedy is required by applicable law or the charge was duplicate or incorrect."] },
      { title: "Deadlines, cancellation, and refunds", body: ["If ApplyPack misses a contractual 24-clock-hour deadline for a reason within ApplyPack's control, you may cancel the unfinished affected item and receive a refund for that unfinished item. Duplicate or incorrect charges are corrected. Other cancellation requests depend on whether work has begun and whether the item remains unfinished. Once the applicable search or document deliverable has been delivered, that completed item is non-refundable; post-delivery remedies are the included factual-correction round or an eligible no-charge job replacement, not a refund. Nothing in these terms removes a non-waivable remedy required by applicable law."] },
      { title: "No outcome guarantee", body: ["ApplyPack does not guarantee ATS ranking, employer review, interviews, offers, salary, employment, or continued listing availability. Employers control hiring decisions and job availability."] },
      { title: "Liability and changes", body: ["To the extent allowed by law, liability is limited to the amount paid for the service giving rise to the claim. Updates will show a new effective date."] },
    ], ctaLabel: "Contact Help", ctaHref: "mailto:help@applypack.work",
  },
};
