import {describe,it,expect} from "vitest";
import {assertCurrentCoverageAuthority} from "@/lib/matching/coverage-authority";
const now=Date.parse("2026-09-22T12:00:00Z");
function fixture(){return {now,cells:[{id:"cell",source_id:"official-source",source_authorization_id:"auth",configuration_id:"config",authorization_mode:"AUTHORIZED_MANUAL_ONLY",execution_path:"MANUAL",authorization:{state:"AUTHORIZED_MANUAL_ONLY"},terminal_outcome:"SUCCEEDED_EMPTY",pagination_bound:2,result_bound:10,lookback_bound:"1 day"}],heads:[{source_id:"official-source",current_authorization_id:"auth",revision:3}],configurations:[{id:"config",source_authorization_id:"auth",pagination_bound:2,result_bound:10,lookback_bound:"1 day"}],manualReviews:[{cell_id:"cell",source_authorization_id:"auth",authorization_head_revision:3,reviewed_at:"2026-09-22T11:00:00Z"}],automatedReviews:[] as Record<string,unknown>[],runs:[] as Record<string,unknown>[]};}
describe("feasibility current source evidence",()=>{
 it("accepts current exact manual policy and attributed receipt",()=>expect(()=>assertCurrentCoverageAuthority(fixture())).not.toThrow());
 it("rejects revoked/replaced authorization even though historical state remains authorized",()=>{const f=fixture();f.heads[0].current_authorization_id="revoked-policy";expect(()=>assertCurrentCoverageAuthority(f)).toThrow("feasibility_current_source_policy_required");});
 it("rejects same authorization restored under a newer head revision",()=>{const f=fixture();f.heads[0].revision=4;expect(()=>assertCurrentCoverageAuthority(f)).toThrow("feasibility_current_source_receipt_required");});
 it("rejects mismatched source configuration bounds",()=>{const f=fixture();f.configurations[0].result_bound=11;expect(()=>assertCurrentCoverageAuthority(f)).toThrow("feasibility_current_source_policy_required");});
 it("rejects missing, old or future manual receipts",()=>{for(const timestamp of ["2026-09-20T11:00:00Z","2026-09-23T11:00:00Z","invalid"]){const f=fixture();f.manualReviews[0].reviewed_at=timestamp;expect(()=>assertCurrentCoverageAuthority(f)).toThrow("feasibility_current_source_receipt_required");}const f=fixture();f.manualReviews=[];expect(()=>assertCurrentCoverageAuthority(f)).toThrow();});
 it("keeps pending work pending without manufacturing a completion receipt",()=>{const f=fixture();f.cells[0].terminal_outcome="PENDING";f.manualReviews=[];expect(()=>assertCurrentCoverageAuthority(f)).not.toThrow();});
 it("rejects a resumed final segment as exhaustive automatic coverage",()=>{const f=fixture();f.cells[0].execution_path="AUTOMATED";f.cells[0].authorization_mode="AUTHORIZED_AUTOMATED";f.cells[0].authorization.state="AUTHORIZED_AUTOMATED";f.automatedReviews=[{cell_id:"cell",source_run_id:"run"}];f.runs=[{id:"run",source_id:"official-source",source_authorization_id:"auth",authorization_head_revision:3,status:"succeeded",enumeration_status:"complete",completed_at:"2026-09-22T11:00:00Z",checkpoint_start:{offset:10}}];expect(()=>assertCurrentCoverageAuthority(f)).toThrow("feasibility_complete_run_receipt_required");f.runs[0].checkpoint_start=null;expect(()=>assertCurrentCoverageAuthority(f)).not.toThrow();});
});
