"use client";
import {useState} from "react";
export function CandidateQuestions({signedIn=false}:{signedIn?:boolean}){
 const [questions,setQuestions]=useState<Array<{id:string;prompt:string}>>([]);const [answers,setAnswers]=useState<Record<string,string>>({});const [confirmed,setConfirmed]=useState<Record<string,boolean>>({});const [status,setStatus]=useState("");
 const endpoint=signedIn?"/api/customer/candidate-questions":"/api/intake/anonymous-draft/questions";
 async function load(){try{const r=await fetch(endpoint,{cache:"no-store"});const data=await r.json();setQuestions((data.questions||[]).filter((q:{answered?:boolean})=>!q.answered));setStatus(r.ok?(data.questions?.length?"Answer only what you know. Uncertain information can remain unknown.":"No clarification questions."):"Questions unavailable.");}catch{setStatus("Questions unavailable. Try again.");}}
 async function answer(id:string){try{const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({questionId:id,answer:answers[id],confirmed:confirmed[id]})});const data=await r.json();if(r.ok)setQuestions(current=>current.filter(q=>q.id!==id));setStatus(r.ok?"Answer saved for evidence review. This does not change a job requirement. Contact support if you need to correct it.":data.error);}catch{setStatus("Answer unavailable. Your text remains here.");}}
 return <section><h2>Questions about your experience</h2><button onClick={load}>Check saved profile questions</button>{questions.map(q=><div key={q.id}><label>{q.prompt}<textarea value={answers[q.id]||""} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})}/></label><label><input type="checkbox" checked={!!confirmed[q.id]} onChange={e=>setConfirmed({...confirmed,[q.id]:e.target.checked})}/>I confirm this answer accurately describes my experience.</label><button disabled={!confirmed[q.id]||!answers[q.id]?.trim()} onClick={()=>answer(q.id)}>Send factual answer</button></div>)}<p role="status">{status}</p></section>;
}
